/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "FHEM Telnet IP:": {                             "en": "FHEM Telnet IP",                                  "de": "FHEM Telnet IP",                                  "ru": "FHEM Telnet IP:",                                 "pt": "FHEM Telnet IP",                                  "nl": "FHEM Telnet IP",                                  "fr": "FHEM Telnet IP",                                  "it": "FHEM Telnet IP",                                  "es": "FHEM Telnet IP",                                  "pl": "FHEM Telnet IP",                                  "zh-cn": "FHEM Telnet IP"},
    "FHEM Telnet Port:": {                           "en": "FHEM Telnet Port",                                "de": "FHEM Telnet Port",                                "ru": "FHEM Telnet порт:",                               "pt": "Porta Telnet FHEM",                               "nl": "FHEM Telnet Port:",                               "fr": "Port Telnet FHEM",                                "it": "FHEM Telnet Port",                                "es": "FHEM Telnet Port",                                "pl": "Port Telnet FHEM",                                "zh-cn": "FHEM Telnet 端口"},
    "FHEM adapter settings": {                       "en": "FHEM adapter settings",                           "de": "FHEM Adapter Einstellungen",                      "ru": "Настройки драйвера FHEM",                         "pt": "Configurações do adaptador FHEM",                 "nl": "FHEM adapter settings",                           "fr": "Paramètres de l'adaptateur FHEM",                 "it": "Impostazioni dell'adattatore FHEM",               "es": "Configuración del adaptador FHEM",                "pl": "Ustawienia adaptera FHEM",                        "zh-cn": "FHEM 适配器设置"},
    "Password repeat:": {                            "en": "Password repeat",                                 "de": "Kennwort-Wiederholung",                           "ru": "Подтверждение пароля:",                           "pt": "Repetição de senha",                              "nl": "Password repeat:",                                "fr": "Répéter le mot de passe",                         "it": "Ripetizione della password",                      "es": "Repite la contraseña",                            "pl": "Powtórz hasło",                                   "zh-cn": "密码重复"},
    "Password:": {                                   "en": "Password",                                        "de": "Kennwort",                                        "ru": "Пароль:",                                         "pt": "Senha",                                           "nl": "Password:",                                       "fr": "Mot de passe",                                    "it": "Parola d'ordine",                                 "es": "Contraseña",                                      "pl": "Hasło",                                           "zh-cn": "密码"},
    "Passwords mismatch!": {                         "en": "Password mismatch!",                              "de": "Kennwörter sind unterschiedlich!",                "ru": "Пароли не совпадают!",                            "pt": "Senha incorreta!",                                "nl": "Password mismatch!",                              "fr": "Non concordance des mots de passe!",              "it": "Mancata corrispondenza delle password!",          "es": "¡Contraseña no coincide!",                        "pl": "Hasło różni się!",                                "zh-cn": "密码不匹配！"},
    "Prompt:": {                                     "en": "Prompt",                                          "de": "Prompt",                                          "ru": "Промпт:",                                         "pt": "Pronto",                                          "nl": "Prompt:",                                         "fr": "Rapide",                                          "it": "Richiesta",                                       "es": "Rápido",                                          "pl": "Skłonić",                                         "zh-cn": "迅速的"},
    "tooltip_password": {                            "en": "Optional. Only if FHEM requires password.",       "de": "Optional. Nur falls in FHEM konfiguriert",        "ru": "Не обязательно. Только если настроено в FHEM",    "pt": "Opcional. Apenas se o FHEM exigir senha.",        "nl": "Optional. Only if FHEM requires password.",       "fr": "Optionnel. Seulement si FHEM nécessite un mot de passe.", "it": "Opzionale. Solo se FHEM richiede una password.",  "es": "Opcional. Solo si FHEM requiere contraseña.",     "pl": "Opcjonalny. Tylko jeśli FHEM wymaga hasła.",      "zh-cn": "可选的。"},
    "tooltip_prompt": {                              "en": "You can change standard prompt from 'fhem>' to something else.", "de": "Man kann hier ein eigenes Prompt setzen. Default ist 'fhem>'", "ru": "Можно задать собственный промпт. По умолчанию 'fhem>'", "pt": "Você pode alterar o prompt padrão de 'fhem>' para outra coisa.", "nl": "You can change standard prompt from 'fhem>' to something else.", "fr": "Vous pouvez changer l'invite standard de 'fhem>' à autre chose.", "it": "Puoi cambiare prompt standard da 'fhem>' a qualcos'altro.", "es": "Puede cambiar la solicitud estándar de 'fhem>' a otra cosa.", "pl": "Możesz zmienić standardowy znak zachęty z 'fhem>' na coś innego.", "zh-cn": "您可以将标准提示从 'fhem>' 更改为其他内容。"},
};